# Generated by Django 5.1.2 on 2025-03-07 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('monthly_stock', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('In Progress', 'Inprogress'), ('Preparing', 'Preparing'), ('Canceled', 'Canceled')], max_length=11)),
                ('members', models.ManyToManyField(blank=True, related_name='fund_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
