# Generated by Django 5.1.2 on 2025-03-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='monthly_stock',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Finished', 'Finished'), ('In Progress', 'Inprogress'), ('Preparing', 'Preparing'), ('Canceled', 'Canceled')], default=('New', 'New'), max_length=11),
        ),
    ]
