# Generated by Django 5.1.2 on 2025-03-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_alter_fund_monthly_stock_alter_fund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='logo',
            field=models.ImageField(default='images/logos/fundLogo.jpg', upload_to='images/logos'),
        ),
    ]
