# Generated by Django 5.1.2 on 2025-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_alter_fund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('finished', 'Finished'), ('inProgress', 'In Progress'), ('preparing', 'Preparing'), ('canceled', 'Canceled')], default='new', max_length=11),
        ),
    ]
