# Generated by Django 5.1.2 on 2025-03-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
